# Generated by Django 5.1.3 on 2024-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lawyers_photos/'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
